/**
 * Fetches Cornell club data from the CampusGroups RSS feed and writes
 * a static data file to frontend/constants/clubs.ts
 *
 * Run with: npx tsx scripts/fetch-clubs.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const RSS_URL = 'https://cornell.campusgroups.com/rss_groups';
const OUTPUT_PATH = path.resolve(__dirname, '../frontend/constants/clubs.ts');

interface Club {
  name: string;
  category: string;
}

function extractTag(xml: string, tag: string): string {
  const match = xml.match(new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`));
  return match ? match[1].trim() : '';
}

function decodeHtmlEntities(str: string): string {
  return str
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'");
}

async function main() {
  console.log('Fetching RSS feed...');
  const res = await fetch(RSS_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);

  const xml = await res.text();

  const itemMatches = xml.match(/<item>([\s\S]*?)<\/item>/g);
  if (!itemMatches) throw new Error('No items found in feed');

  const clubs: Club[] = itemMatches
    .map((item) => {
      const name = decodeHtmlEntities(extractTag(item, 'groupName'));
      const rawCategory = extractTag(item, 'category');
      // Category can be semicolon-separated — use the first one
      const category = decodeHtmlEntities(rawCategory.split(',')[0].trim());
      return { name, category };
    })
    .filter((c) => c.name.length > 0)
    .sort((a, b) => a.name.localeCompare(b.name));

  const output = `// Auto-generated by scripts/fetch-clubs.ts — do not edit manually
// Source: ${RSS_URL}
// Last updated: ${new Date().toISOString()}

export interface Club {
  name: string;
  category: string;
}

export const CLUBS: Club[] = ${JSON.stringify(clubs, null, 2)};
`;

  fs.writeFileSync(OUTPUT_PATH, output, 'utf-8');
  console.log(`Done. Wrote ${clubs.length} clubs to ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
